export default {}
export const BOOK_LIST_GET = 'BOOK_LIST_GET'
export const BOOK_LIST_POST = 'BOOK_LIST_POST'
export const BOOK_LIST_DELETE = 'BOOK_LIST_DELETE'
export const BOOK_LIST_PUT = 'BOOK_LIST_PUT'

export const CATALOGS_GET = 'CATALOGS_GET'
export const CATALOGS_POST = 'CATALOGS_POST'
export const CATALOGS_DELETE = 'CATALOGS_DELETE'
export const CATALOGS_PUT = 'CATALOGS_PUT'

export const SCHEMA_LIST_GET = 'SCHEMA_LIST_GET'
export const SCHEMA_DETAIL_GET = 'SCHEMA_DETAIL_GET'
export const SCHEMA_DELETE = 'SCHEMA_DELETE'
export const SCHEMA_POST = 'SCHEMA_POST'
export const SCHEMA_PUT = 'SCHEMA_PUT'
export const SCHEMA_FIELD_POST = 'SCHEMA_FIELD_POST'
export const SCHEMA_FIELD_PUT = 'SCHEMA_FIELD_PUT'
export const SCHEMA_FIELD_DELETE = 'SCHEMA_FIELD_DELETE'
