export const BOOK_LIST_SAVE = 'BOOK_LIST_SAVE'
export const BOOK_LIST_UPDATE = 'BOOK_LIST_UPDATE'
export const BOOK_CUR_UPDATE = 'BOOK_CUR_UPDATE'

export const CATALOGS_SAVE = 'CATALOGS_SAVE'
export const CATALOGS_CUR_SAVE = 'CATALOGS_CUR_SAVE'
export const CATALOGS_TEMPLATE_CREATE = 'CATALOGS_TEMPLATE_CREATE'

// schema

export const SCHEMA_LIST_SAVE = 'SCHEMA_LIST_SAVE'
export const SCHEMA_LIST_UPDATE = 'SCHEMA_LIST_UPDATE'
export const SCHEMA_CUR_SAVE = 'SCHEMA_CUR_SAVE'
